### ISSUE TITLE
同步 nonebot-plugin-with-ai-agents==0.1.15 新特性

### ISSUE THREAD

**Issue by gfhdhytghd** [yejue/with-ai-agents#1]
很抱歉打扰您,如果作者大大有时间的话,我希望宁可以更新一下此仓库,加入nonebot-plugin-with-ai-agents中的那些新功能

我在我自己的一个项目中使用了您的库,使用体验非常好,但是我仍然希望可以使用更新的功能,而我的技术实力又不支持我独立完成这些工作

**Comment by yejue** [comment]
可以，不过新特性不少，你可以说一下哪些是比较需要的，我可以优先更新（有空的时候）

**Comment by gfhdhytghd** [comment]
感谢,以下需求按重要性排序:

prompt设置
连续对话与清屏

联网结果提取优化：修复 (Invalid \escape)、增加 V2 版本结果提取
联网搜索优化：使用宽泛化的搜索提高搜索成功率和获得更好的搜索答案

回复优化：提高最终回复时的联想能力
百度百科搜索能力

**Comment by gfhdhytghd** [comment]
我还希望特可以在某些设置之后拥有调用其他bot的能力,比如在问天气的时候,他可以 @小小萌 天气 [城市]
(通过curl访问http://127.0.0.1:xxxx/send_group_massege?group_id={groupid}&messege="[CQ:at,id=xxxxx] 天气 [城市]")

**Comment by yejue** [comment]
当前模块已经同步了 nonebot-plugin-with-ai-agents 的所有特性，此次更新为破坏性更新，完全区别于在 nb 环境下的模块，如果要更新请先阅读使用文档

**Comment by gfhdhytghd** [comment]
感谢
